robot:
  ip: "192.168.11.5"
  start_pose: [0, -0.4, 0.3, 3.14, 0, 0]

force_mode:
  selection_vector: [1, 1, 1, 0, 0, 0]
  type: 2
  limits: [10, 10, 10, 1, 1, 1]
  damping: 0.003
  gain_scaling: 1.0
  threshold: 7.0

logging:
  out_dir: "outputs"
